opnsense:
  enabled: False
  url: "https://{OPNSENSE_URL}"
  api_key: "{API_KEY}:{API_SECRET}"  # Or api_key_secret: true with --set-secret opnsense
  # api_key_secret: true
  ssl: True
  verifycert: False
  default_interface: "wan"
  accepts:
    - ip-dst
  returns:
    - ip-dst
    - opnsense-rule-uuid
    - opnsense-firewall-status
  playbook_functions:
    - add_firewall_rule
    - delete_firewall_rule
    - apply_changes
    - get_firewall_status
